version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: efgs-federation-gateway-mysql
    environment:
      - MYSQL_DATABASE=fg
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=fg_adm
      - MYSQL_PASSWORD=admin
    networks:
      persistence:
        aliases:
          - mysql
  backend:
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fg
    depends_on:
      - mysql
